var tableauQuestion = [
        {   question : "Se você estiver dirigindo a 80 kmh, e você se aproxima de uma área residencial, isso significa que:",
            propositionA : "Você terá que acelerar a frente",
            propositionB : "Você pode acelerar contanto que não existam outros carros",
            propositionC : "Você terá que diminuir a velocidade logo a frente",
            propositionD : "Você pode manter sua velocidade",
            reponse : "C"},
                    
        {   question : "Ao girar à esquerda em um sinal verde, você vê que um pedestre está no cruzamento. Quem tem o direito de passagem?",
            propositionA : "O pedestre, porque eles podem atravessar a estrada com qualquer sinal",
            propositionB : "Seu veículo porque o sinal está verde",
            propositionC : "O pedestre, porque ele atravessa o sinal verde",
            propositionD : "Seu veículo, porque os veículos tem direitos de passagem",
            reponse : "B"},
                    
        {   question : "A menos que dito, a velocidade máxima em uma área residencial é ____ kmh.",
            propositionA : "50",
            propositionB : "55",
            propositionC : "65",
            propositionD : "70",
            reponse : "A"},
            
            {   question : "Antes de mudar de faixa você deverá:",
            propositionA : "Checar seus retrovisores",
            propositionB : "Checar o seu ponto cego",
            propositionC : "Sinalizar suas intenções",
            propositionD : "Todas as alternativas anteriores",
            reponse : "D"},
                    
            {   question : "Qual o limite de álcool no sangue?",
            propositionA : "0.05%",
            propositionB : "0.18%",
            propositionC : "0.08%",
            propositionD : "0.06%",
            reponse : "C"},
                    
            {   question : "Você deve parar e estacionar enquanto uma ambulÂncia está passando a menos que",
            propositionA : "Você esteja com pressa",
            propositionB : "Exista pista vazia pra ela",
            propositionC : "Você eteja em uma zona escolar",
            propositionD : "Você esteja em uma interseção",
            reponse : "B"},
            
            {   question : "O direito de passagem deve ser cedido aos veículos de emergência quando:",
            propositionA : "Em todo momento",
            propositionB : "Luzes vermelhas, azuis ou brancas intermitentes",
            propositionC : "Usando uma sirene ou piscando luzes vermelhas, azuis ou brancas",
            propositionD : "Usando uma sirene",
            reponse : "C"},
                    
            {   question : "Qual das seguintes condições é permitida ao passar por outro veículo?",
            propositionA : "Seguir bem de preto",
            propositionB : "Saindo da estrada principal percorrida",
            propositionC : "Dirigindo no lado oposto da rodovia",
            propositionD : "Excedendo o limite de velocidade",
            reponse : "C"},
                    
            {   question : "Você está dirigindo em uma auto-estrada com um limite de velocidade de 110 kmh. A maioria do tráfego está viajando a 120 mph, então você não deve dirigir mais rápido que:",
            propositionA : "80 kmh",
            propositionB : "40 kmh",
            propositionC : "50 kmh",
            propositionD : "110 kmh",
            reponse : "D"},
                    
            {   question : "Ao ser ultrapassado por outro veículo, é importante não:",
            propositionA : "Desacelerar",
            propositionB : "Checar seus retrovisores",
            propositionC : "Ficar olhando pro outro motorista",
            propositionD : "Acelerar",
            reponse : "D"},
    ]
    